import Dashbord from "@/components/adminDashbord/content/dashbord/dashbord";
import Layout from "@/components/adminDashbord/layout/layout";
import AdminUserManagment from "@/components/adminUserManagment";
import { useAdminNav } from "@/store/adminNav";
import Head from "next/head";

export default function Home() {
  const { currentItem } = useAdminNav();
  return (
    <>
      <Head>
        <title>TLOU -Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-full  rounded-xl ">
        {currentItem == "Dashboard" && <Dashbord />}
        {currentItem == "User Management" && <AdminUserManagment />}
      </main>
    </>
  );
}
