import { useState } from "react";
export const allTimeZnes = [
  { time: "Africa/Abidjan" },
  { time: "Africa/Accra" },
  { time: "Africa/Addis_Ababa" },
  { time: "Africa/Algiers" },
  { time: "Africa/Asmara" },
  { time: "Africa/Bamako" },
  { time: "Africa/Bangui" },
  { time: "Africa/Banjul" },
  { time: "Africa/Bissau" },
  { time: "Africa/Blantyre" },
  { time: "Africa/Brazzaville" },
  { time: "Africa/Bujumbura" },
  { time: "Africa/Cairo" },
  { time: "Africa/Casablanca" },
  { time: "Africa/Ceuta" },
  { time: "Africa/Conakry" },
  { time: "Africa/Dakar" },
  { time: "Africa/Dar_es_Salaam" },
  { time: "Africa/Djibouti" },
  { time: "Africa/Douala" },
  { time: "Africa/El_Aaiun" },
  { time: "Africa/Freetown" },
  { time: "Africa/Gaborone" },
  { time: "Africa/Harare" },
  { time: "Africa/Johannesburg" },
  { time: "Africa/Juba" },
  { time: "Africa/Kampala" },
  { time: "Africa/Khartoum" },
  { time: "Africa/Kigali" },
  { time: "Africa/Kinshasa" },
  { time: "Africa/Lagos" },
  { time: "Africa/Libreville" },
  { time: "Africa/Lome" },
  { time: "Africa/Luanda" },
  { time: "Africa/Lubumbashi" },
  { time: "Africa/Lusaka" },
  { time: "Africa/Malabo" },
  { time: "Africa/Maputo" },
  { time: "Africa/Maseru" },
  { time: "Africa/Mbabane" },
  { time: "Africa/Mogadishu" },
  { time: "Africa/Monrovia" },
  { time: "Africa/Nairobi" },
  { time: "Africa/Ndjamena" },
  { time: "Africa/Niamey" },
  { time: "Africa/Nouakchott" },
  { time: "Africa/Ouagadougou" },
  { time: "Africa/Porto-Novo" },
  { time: "Africa/Sao_Tome" },
  { time: "Africa/Tripoli" },
  { time: "Africa/Tunis" },
  { time: "Africa/Windhoek" },
  { time: "America/Adak" },
  { time: "America/Anchorage" },
  { time: "America/Anguilla" },
  { time: "America/Antigua" },
  { time: "America/Araguaina" },
  { time: "America/Argentina/Buenos_Aires" },
  { time: "America/Argentina/Catamarca" },
  { time: "America/Argentina/Cordoba" },
  { time: "America/Argentina/Jujuy" },
  { time: "America/Argentina/La_Rioja" },
  { time: "America/Argentina/Mendoza" },
  { time: "America/Argentina/Rio_Gallegos" },
  { time: "America/Argentina/Salta" },
  { time: "America/Argentina/San_Juan" },
  { time: "America/Argentina/San_Luis" },
  { time: "America/Argentina/Tucuman" },
  { time: "America/Argentina/Ushuaia" },
  { time: "America/Aruba" },
  { time: "America/Asuncion" },
  { time: "America/Atikokan" },
  { time: "America/Bahia" },
  { time: "America/Bahia_Banderas" },
  { time: "America/Barbados" },
  { time: "America/Belem" },
  { time: "America/Belize" },
  { time: "America/Blanc-Sablon" },
  { time: "America/Boa_Vista" },
  { time: "America/Bogota" },
  { time: "America/Boise" },
  { time: "America/Cambridge_Bay" },
  { time: "America/Campo_Grande" },
  { time: "America/Cancun" },
  { time: "America/Caracas" },
  { time: "America/Cayenne" },
  { time: "America/Cayman" },
  { time: "America/Chicago" },
  { time: "America/Chihuahua" },
  { time: "America/Costa_Rica" },
  { time: "America/Creston" },
  { time: "America/Cuiaba" },
  { time: "America/Curacao" },
  { time: "America/Danmarkshavn" },
  { time: "America/Dawson" },
  { time: "America/Dawson_Creek" },
  { time: "America/Denver" },
  { time: "America/Detroit" },
  { time: "America/Dominica" },
  { time: "America/Edmonton" },
  { time: "America/Eirunepe" },
  { time: "America/El_Salvador" },
  { time: "America/Fort_Nelson" },
  { time: "America/Fortaleza" },
  { time: "America/Glace_Bay" },
  { time: "America/Godthab" },
  { time: "America/Goose_Bay" },
  { time: "America/Grand_Turk" },
  { time: "America/Grenada" },
  { time: "America/Guadeloupe" },
  { time: "America/Guatemala" },
  { time: "America/Guayaquil" },
  { time: "America/Guyana" },
  { time: "America/Halifax" },
  { time: "America/Havana" },
  { time: "America/Hermosillo" },
  { time: "America/Indiana/Indianapolis" },
  { time: "America/Indiana/Knox" },
  { time: "America/Indiana/Marengo" },
  { time: "America/Indiana/Petersburg" },
  { time: "America/Indiana/Tell_City" },
  { time: "America/Indiana/Vevay" },
  { time: "America/Indiana/Vincennes" },
  { time: "America/Indiana/Winamac" },
  { time: "America/Inuvik" },
  { time: "America/Iqaluit" },
  { time: "America/Jamaica" },
  { time: "America/Juneau" },
  { time: "America/Kentucky/Louisville" },
  { time: "America/Kentucky/Monticello" },
  { time: "America/Kralendijk" },
  { time: "America/La_Paz" },
  { time: "America/Lima" },
  { time: "America/Los_Angeles" },
  { time: "America/Lower_Princes" },
  { time: "America/Maceio" },
  { time: "America/Managua" },
  { time: "America/Manaus" },
  { time: "America/Marigot" },
  { time: "America/Martinique" },
  { time: "America/Matamoros" },
  { time: "America/Mazatlan" },
  { time: "America/Menominee" },
  { time: "America/Merida" },
  { time: "America/Metlakatla" },
  { time: "America/Mexico_City" },
  { time: "America/Miquelon" },
  { time: "America/Moncton" },
  { time: "America/Monterrey" },
  { time: "America/Montevideo" },
  { time: "America/Montserrat" },
  { time: "America/Nassau" },
  { time: "America/New_York" },
  { time: "America/Nipigon" },
  { time: "America/Nome" },
  { time: "America/Noronha" },
  { time: "America/North_Dakota/Beulah" },
  { time: "America/North_Dakota/Center" },
  { time: "America/North_Dakota/New_Salem" },
  { time: "America/Nuuk" },
  { time: "America/Ojinaga" },
  { time: "America/Panama" },
  { time: "America/Pangnirtung" },
  { time: "America/Paramaribo" },
  { time: "America/Phoenix" },
  { time: "America/Port-au-Prince" },
  { time: "America/Port_of_Spain" },
  { time: "America/Porto_Velho" },
  { time: "America/Puerto_Rico" },
  { time: "America/Punta_Arenas" },
  { time: "America/Rainy_River" },
  { time: "America/Rankin_Inlet" },
  { time: "America/Recife" },
  { time: "America/Regina" },
  { time: "America/Resolute" },
  { time: "America/Rio_Branco" },
  { time: "America/Santarem" },
  { time: "America/Santiago" },
  { time: "America/Santo_Domingo" },
  { time: "America/Sao_Paulo" },
  { time: "America/Scoresbysund" },
  { time: "America/Sitka" },
  { time: "America/St_Barthelemy" },
  { time: "America/St_Johns" },
  { time: "America/St_Kitts" },
  { time: "America/St_Lucia" },
  { time: "America/St_Thomas" },
  { time: "America/St_Vincent" },
  { time: "America/Swift_Current" },
  { time: "America/Tegucigalpa" },
  { time: "America/Thule" },
  { time: "America/Thunder_Bay" },
  { time: "America/Tijuana" },
  { time: "America/Toronto" },
  { time: "America/Tortola" },
  { time: "America/Vancouver" },
  { time: "America/Whitehorse" },
  { time: "America/Winnipeg" },
  { time: "America/Yakutat" },
  { time: "America/Yellowknife" },
  { time: "Antarctica/Casey" },
  { time: "Antarctica/Davis" },
  { time: "Antarctica/DumontDUrville" },
  { time: "Antarctica/Macquarie" },
  { time: "Antarctica/Mawson" },
  { time: "Antarctica/McMurdo" },//////
  { time: "Antarctica/Palmer" },
  { time: "Antarctica/Rothera" },
  { time: "Antarctica/Syowa" },
  { time: "Antarctica/Troll" },
  { time: "Antarctica/Vostok" },
  { time: "Arctic/Longyearbyen" },
  { time: "Asia/Aden" },
  { time: "Asia/Almaty" },
  { time: "Asia/Amman" },
  { time: "Asia/Anadyr" },
  { time: "Asia/Aqtau" },
  { time: "Asia/Aqtobe" },
  { time: "Asia/Ashgabat" },
  { time: "Asia/Atyrau" },
  { time: "Asia/Baghdad" },
  { time: "Asia/Bahrain" },
  { time: "Asia/Baku" },
  { time: "Asia/Bangkok" },
  { time: "Asia/Barnaul" },
  { time: "Asia/Beirut" },
  { time: "Asia/Bishkek" },
  { time: "Asia/Brunei" },
  { time: "Asia/Chita" },
  { time: "Asia/Choibalsan" },
  { time: "Asia/Colombo" },
  { time: "Asia/Damascus" },
  { time: "Asia/Dhaka" },
  { time: "Asia/Dili" },
  { time: "Asia/Dubai" },
  { time: "Asia/Dushanbe" },
  { time: "Asia/Famagusta" },
  { time: "Asia/Gaza" },
  { time: "Asia/Hebron" },
  { time: "Asia/Ho_Chi_Minh" },
  { time: "Asia/Hong_Kong" },
  { time: "Asia/Hovd" },
  { time: "Asia/Irkutsk" },
  { time: "Asia/Jakarta" },
  { time: "Asia/Jayapura" },
  { time: "Asia/Jerusalem" },
  { time: "Asia/Kabul" },
  { time: "Asia/Kamchatka" },
  { time: "Asia/Karachi" },
  { time: "Asia/Kathmandu" },
  { time: "Asia/Khandyga" },
  { time: "Asia/Kolkata" },
  { time: "Asia/Krasnoyarsk" },
  { time: "Asia/Kuala_Lumpur" },
  { time: "Asia/Kuching" },
  { time: "Asia/Kuwait" },
  { time: "Asia/Macau" },
  { time: "Asia/Magadan" },
  { time: "Asia/Makassar" },
  { time: "Asia/Manila" },
  { time: "Asia/Muscat" },
  { time: "Asia/Nicosia" },
  { time: "Asia/Novokuznetsk" },
  { time: "Asia/Novosibirsk" },
  { time: "Asia/Omsk" },
  { time: "Asia/Oral" },
  { time: "Asia/Phnom_Penh" },
  { time: "Asia/Pontianak" },
  { time: "Asia/Pyongyang" },
  { time: "Asia/Qatar" },
  { time: "Asia/Qyzylorda" },
  { time: "Asia/Riyadh" },
  { time: "Asia/Sakhalin" },
  { time: "Asia/Samarkand" },
  { time: "Asia/Seoul" },
  { time: "Asia/Shanghai" },
  { time: "Asia/Singapore" },
  { time: "Asia/Srednekolymsk" },
  { time: "Asia/Taipei" },
  { time: "Asia/Tashkent" },
  { time: "Asia/Tbilisi" },
  { time: "Asia/Tehran" },
  { time: "Asia/Thimphu" },
  { time: "Asia/Tokyo" },
  { time: "Asia/Tomsk" },
  { time: "Asia/Ulaanbaatar" },
  { time: "Asia/Urumqi" },
  { time: "Asia/Ust-Nera" },
  { time: "Asia/Vientiane" },
  { time: "Asia/Vladivostok" },
  { time: "Asia/Yakutsk" },
  { time: "Asia/Yangon" },
  { time: "Asia/Yekaterinburg" },
  { time: "Asia/Yerevan" },
  { time: "Atlantic/Azores" },
  { time: "Atlantic/Bermuda" },
  { time: "Atlantic/Canary" },
  { time: "Atlantic/Cape_Verde" },
  { time: "Atlantic/Faroe" },
  { time: "Atlantic/Madeira" },
  { time: "Atlantic/Reykjavik" },
  { time: "Atlantic/South_Georgia" },
  { time: "Atlantic/St_Helena" },
  { time: "Atlantic/Stanley" },
  { time: "Australia/Adelaide" },
  { time: "Australia/Brisbane" },
  { time: "Australia/Broken_Hill" },
  { time: "Australia/Currie" },
  { time: "Australia/Darwin" },
  { time: "Australia/Eucla" },
  { time: "Australia/Hobart" },
  { time: "Australia/Lindeman" },
  { time: "Australia/Lord_Howe" },
  { time: "Australia/Melbourne" },
  { time: "Australia/Perth" },
  { time: "Australia/Sydney" },
  { time: "Europe/Amsterdam" },
  { time: "Europe/Andorra" },
  { time: "Europe/Astrakhan" },
  { time: "Europe/Athens" },
  { time: "Europe/Belgrade" },
  { time: "Europe/Berlin" },
  { time: "Europe/Bratislava" },
  { time: "Europe/Brussels" },
  { time: "Europe/Bucharest" },
  { time: "Europe/Budapest" },
  { time: "Europe/Busingen" },
  { time: "Europe/Chisinau" },
  { time: "Europe/Copenhagen" },
  { time: "Europe/Dublin" },
  { time: "Europe/Gibraltar" },
  { time: "Europe/Guernsey" },
  { time: "Europe/Helsinki" },
  { time: "Europe/Isle_of_Man" },
  { time: "Europe/Istanbul" },
  { time: "Europe/Jersey" },
  { time: "Europe/Kaliningrad" },
  { time: "Europe/Kiev" },
  { time: "Europe/Kirov" },
  { time: "Europe/Lisbon" },
  { time: "Europe/Ljubljana" },
  { time: "Europe/London" },
  { time: "Europe/Luxembourg" },
  { time: "Europe/Madrid" },
  { time: "Europe/Malta" },
  { time: "Europe/Mariehamn" },
  { time: "Europe/Minsk" },
  { time: "Europe/Monaco" },
  { time: "Europe/Moscow" },
  { time: "Europe/Oslo" },
  { time: "Europe/Paris" },
  { time: "Europe/Podgorica" },
  { time: "Europe/Prague" },
  { time: "Europe/Riga" },
  { time: "Europe/Rome" },
  { time: "Europe/Samara" },
  { time: "Europe/San_Marino" },
  { time: "Europe/Sarajevo" },
  { time: "Europe/Saratov" },
  { time: "Europe/Simferopol" },
  { time: "Europe/Skopje" },
  { time: "Europe/Sofia" },
  { time: "Europe/Stockholm" },
  { time: "Europe/Tallinn" },
  { time: "Europe/Tirane" },
  { time: "Europe/Ulyanovsk" },
  { time: "Europe/Uzhgorod" },
  { time: "Europe/Vaduz" },
  { time: "Europe/Vatican" },
  { time: "Europe/Vienna" },
  { time: "Europe/Vilnius" },
  { time: "Europe/Volgograd" },
  { time: "Europe/Warsaw" },
  { time: "Europe/Zagreb" },
  { time: "Europe/Zaporozhye" },
  { time: "Europe/Zurich" },
  { time: "Indian/Antananarivo" },
  { time: "Indian/Chagos" },
  { time: "Indian/Christmas" },
  { time: "Indian/Cocos" },
  { time: "Indian/Comoro" },
  { time: "Indian/Kerguelen" },
  { time: "Indian/Mahe" },
  { time: "Indian/Maldives" },
  { time: "Indian/Mauritius" },
  { time: "Indian/Mayotte" },
  { time: "Indian/Reunion" },
  { time: "Pacific/Apia" },
  { time: "Pacific/Auckland" },
  { time: "Pacific/Bougainville" },
  { time: "Pacific/Chatham" },
  { time: "Pacific/Chuuk" },
  { time: "Pacific/Easter" },
  { time: "Pacific/Efate" },
  { time: "Pacific/Enderbury" },
  { time: "Pacific/Fakaofo" },
  { time: "Pacific/Fiji" },
  { time: "Pacific/Funafuti" },
  { time: "Pacific/Galapagos" },
  { time: "Pacific/Gambier" },
  { time: "Pacific/Guadalcanal" },
  { time: "Pacific/Guam" },
  { time: "Pacific/Honolulu" },
  { time: "Pacific/Johnston" },
  { time: "Pacific/Kiritimati" },
  { time: "Pacific/Kosrae" },
  { time: "Pacific/Kwajalein" },
  { time: "Pacific/Majuro" },
  { time: "Pacific/Marquesas" },
  { time: "Pacific/Midway" },
  { time: "Pacific/Nauru" },
  { time: "Pacific/Niue" },
  { time: "Pacific/Norfolk" },
  { time: "Pacific/Noumea" },
  { time: "Pacific/Pago_Pago" },
  { time: "Pacific/Palau" },
  { time: "Pacific/Pitcairn" },
  { time: "Pacific/Pohnpei" },
  { time: "Pacific/Port_Moresby" },
  { time: "Pacific/Rarotonga" },
  { time: "Pacific/Saipan" },
  { time: "Pacific/Tahiti" },
  { time: "Pacific/Tarawa" },
  { time: "Pacific/Tongatapu" },
  { time: "Pacific/Wake" },
  { time: "Pacific/Wallis" },
];



export const AllTimeZones = ({handleTimeZoneChange}) => {
 // const [filter, setFilter] = useState("");
  const [showTimeZones, setShowTimeZones] = useState(false)
  const [timezonesToSelectFrom, settimezonesToSelectFrom] = useState(allTimeZnes)

const handleFilter=(e)=>{

    
        const filter=e.target.value
        const filteredTable = allTimeZnes.filter(row => row.time.toLowerCase().includes(filter.toLowerCase()));
        settimezonesToSelectFrom(filteredTable)
      
      
}

  
  return (
    <div className="h-full w-fit relative ">
      <div className=" flex w-fit mx-auto items-center gap-2">
        <p>Select new time zone</p>
        <svg
        onClick={()=>{setShowTimeZones(!showTimeZones)}}
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth={1.5}
          stroke="currentColor"
          className={`w-6 h-6 hover:cursor-pointer ${showTimeZones?'rotate-180':''}  `}
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M19.5 8.25l-7.5 7.5-7.5-7.5"
          />
        </svg>
      </div>

     {showTimeZones&& <div
     className=" "
     >

      
      <input
        className="block w-[75%] h-10 mx-auto border  pl-[45px] text-md bg-transparent text-[#CFCFE2]   rounded-lg placeholder:text-[#CFCFE2] placeholder:font-roboto placeholder:font-normal placeholder:text-xs " placeholder="Search time zone"
     
        onChange={(e) => {
          
            handleFilter(e)
        }}
      />
      <div 
      style={{
        background:
          "linear-gradient(97.77deg, rgba(30, 30, 30, 1) 1.14%, rgba(30, 30, 30, 1) 100%)",
        boxShadow: "inset 0px 0px 3px rgba(255, 255, 255, 0.31)",
        backdropFilter: "backdrop-filter: blur(28.5px)",
      }}
      
      className="absolute top-16 z-50 rounded-xl   overflow-y-scroll w-full flex items-center scrollbar-hide max-h-96 h-fit  ">
      
        <div className="w-full h-full flex flex-col pt-4">
            {
                timezonesToSelectFrom.map((item,index)=>{

                    return <span onClick={()=>{handleTimeZoneChange(item.time);setShowTimeZones(false)}} className="py-1 border-b border-opacity-25 hover:cursor-pointer hover:font-bold" key={index}>{item.time}</span>
                })
            }
        </div>
      
        </div>
      </div>}
    </div>
  );
};
